### ISSUE TITLE
Not getting notifications of new files on Windows

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/atmosphere_pro#132]
**Describe the bug**
Use Windows !
**To Reproduce**
1 I notice (sometimes the red dot but on MAC I get a real notification)

**Expected behavior**
I real windows notification

**Screenshots**
I noticed this is the logs it may help ?
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Exception: Not initialized, please call `localNotifier.setup` first to initialize
#0      LocalNotifier.notify (package:local_notifier/src/local_notifier.dart:101:7)
#1      LocalNotificationService.showNotification (package:atsign_atmosphere_pro/services/notification_service.dart:109:27)     
#2      HistoryProvider.checkForUpdatedOrNewNotification (package:atsign_atmosphere_pro/view_models/history_provider.dart:519:16)
#3      BackendService._notificationCallBack (package:atsign_atmosphere_pro/services/backend_service.dart:227:14)
<asynchronous suspension>
#4      BackendService.startMonitor.<anonymous closure> (package:atsign_atmosphere_pro/services/backend_service.dart:157:7)     
<asynchronous suspension>
```

**Smartphone (please complete the following information):**
 - Windows 11 
 - Flutter 3.0.2
 - X86_64

**Were you using an @‎application when the bug was found?**
  - [@‎tmospherePro (trunk)

**Additional context**

**Comment by cconstab** [comment]
User error !

Found config in windows to enable
